version: '3.8'

networks:
  app_network:
    name: app_network

services:
  mongodb_server:
    image: mongo:jammy
    container_name: mongodb_server
    hostname: mongodb_server
    networks:
      - app_network
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root_mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=root_mongo_user_password      
    volumes:
      - mongodb_data_container:/data/mongodb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb_server:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  
  mongo-express:
    image: mongo-express:1.0.0-20
    container_name: mongodb_express
    hostname: mongodb_express
    networks:
      - app_network
    restart: always
    depends_on:
      - mongodb_server
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root_mongo_user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root_mongo_user_password
      - ME_CONFIG_MONGODB_SERVER=mongodb_server
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123


volumes:
  mongodb_data_container:


